name: Infra & Deploy (DigitalOcean)

on:
  push:
    branches: [  master, staging ]

env:
  TF_CLOUD_ORGANIZATION: "awakenrise"
  TF_WORKSPACE: "staging"

jobs:
  terraform:
    name: "Terraform & Ansible"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/terraform/environments/staging
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve \
            -var="do_token=${{ secrets.DIGITALOCEAN_TOKEN }}" \
            -var="ssh_key_fingerprint=${{ secrets.SSH_KEY_FINGERPRINT }}"
        working-directory: ./infra/terraform/environments/staging
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}


      - name: Get Infrastructure Outputs
        id: infra_outputs
        run: |
          echo "DROPLET_IP=$(terraform output -raw droplet_ip)" >> $GITHUB_OUTPUT
          echo "MYSQL_HOST=$(terraform output -raw mysql_host)" >> $GITHUB_OUTPUT
          echo "MYSQL_PORT=$(terraform output -raw mysql_port)" >> $GITHUB_OUTPUT
          echo "MYSQL_USER=$(terraform output -raw mysql_user)" >> $GITHUB_OUTPUT
          echo "MYSQL_PASSWORD=$(terraform output -raw mysql_password)" >> $GITHUB_OUTPUT
          echo "REDIS_HOST=$(terraform output -raw redis_host)" >> $GITHUB_OUTPUT
        working-directory: ./infra/terraform/environments/staging

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ steps.infra_outputs.outputs.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Run Ansible
        run: |
          ansible-playbook -i infra/ansible/inventory/staging/hosts.ini \
            infra/ansible/site.yml \
            -e "target_ip=${{ steps.infra_outputs.outputs.DROPLET_IP }}" \
            -e "mysql_host=${{ steps.infra_outputs.outputs.MYSQL_HOST }}" \
            -e "mysql_port=${{ steps.infra_outputs.outputs.MYSQL_PORT }}" \
            -e "mysql_user=${{ steps.infra_outputs.outputs.MYSQL_USER }}" \
            -e "mysql_password=${{ steps.infra_outputs.outputs.MYSQL_PASSWORD }}" \
            -e "redis_host=${{ steps.infra_outputs.outputs.REDIS_HOST }}" \
            -e "rabbitmq_url=${{ secrets.RABBITMQ_URL }}" \
            -e "ansible_ssh_private_key_file=~/.ssh/id_rsa"
