name: Infra & Deploy (DigitalOcean)

on:
  push:
    branches: [  master, staging ]

jobs:
  terraform:
    name: "Terraform & Ansible"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/terraform/environments/staging
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve \
            -var="do_token=${{ secrets.DIGITALOCEAN_TOKEN }}" \
            -var="ssh_key_fingerprint=${{ secrets.SSH_KEY_FINGERPRINT }}"
        working-directory: ./infra/terraform/environments/staging
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}


      - name: Get Infrastructure Outputs
        id: infra_outputs
        run: |
          echo "DROPLET_IP=$(terraform output -raw droplet_ip)" >> $GITHUB_OUTPUT
          echo "MYSQL_HOST=$(terraform output -raw mysql_host)" >> $GITHUB_OUTPUT
          echo "MYSQL_PORT=$(terraform output -raw mysql_port)" >> $GITHUB_OUTPUT
          echo "MYSQL_USER=$(terraform output -raw mysql_user)" >> $GITHUB_OUTPUT
          echo "MYSQL_PASSWORD=$(terraform output -raw mysql_password)" >> $GITHUB_OUTPUT
        working-directory: ./infra/terraform/environments/staging

      - name: Setup SSH Key
        shell: python
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DROPLET_IP: ${{ steps.infra_outputs.outputs.DROPLET_IP }}
        run: |
          import os
          ssh_dir = os.path.expanduser("~/.ssh")
          os.makedirs(ssh_dir, exist_ok=True)
          key_path = os.path.join(ssh_dir, "id_ed25519")
          with open(key_path, "w") as f:
              f.write(os.environ["SSH_KEY"].strip() + "\n")
          os.chmod(key_path, 0o600)
          os.system(f"ssh-keyscan -H {os.environ['DROPLET_IP']} >> {os.path.join(ssh_dir, 'known_hosts')}")
          print("Chave configurada com sucesso!")

      - name: Test SSH Connection
        run: |
          ssh -vvv -o BatchMode=yes -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i /home/runner/.ssh/id_ed25519 root@${{ steps.infra_outputs.outputs.DROPLET_IP }} "echo 'SSH REALMENTE FUNCIONA!'"

      - name: Update Ansible Inventory
        run: |
          sed -i "s/TARGET_IP/${{ steps.infra_outputs.outputs.DROPLET_IP }}/g" infra/ansible/inventory/staging/hosts.ini

      - name: Run Ansible
        run: |
          ansible-playbook -vvv -i infra/ansible/inventory/staging/hosts.ini \
            infra/ansible/site.yml \
            --ssh-extra-args='-o IdentitiesOnly=yes -o PreferredAuthentications=publickey' \
            -e "target_ip=${{ steps.infra_outputs.outputs.DROPLET_IP }}" \
            -e "mysql_host=${{ steps.infra_outputs.outputs.MYSQL_HOST }}" \
            -e "mysql_port=${{ steps.infra_outputs.outputs.MYSQL_PORT }}" \
            -e "mysql_user=${{ steps.infra_outputs.outputs.MYSQL_USER }}" \
            -e "mysql_password=${{ steps.infra_outputs.outputs.MYSQL_PASSWORD }}" \
            -e "redis_url=${{ secrets.UPSTASH_REDIS_URL }}" \
            -e "rabbitmq_url=${{ secrets.RABBITMQ_URL }}" \
            -e "ansible_ssh_private_key_file=/home/runner/.ssh/id_ed25519"
